name: CI/CD - Build e Deploy Azure

on:
  push:
    branches:
      - main


      

env:
  ACR_NAME: crudpythonaulacloud
  IMAGE_NAME: projetoweb
  WEBAPP_NAME: cloudio
  RESOURCE_GROUP: seu-grupo-de-recursos-aqui # <-- ADICIONE ISSO AQUI COM O NOME DO SEU GRUPO

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Login no Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build e Push da imagem Docker
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
                     ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cloudio'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'crudpythonaulacloud.azurecr.io/projetoweb:${{ github.sha }}'
